name = "pluvo"
version = "0.0.1"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "username", repo = "project" }
# links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = "~> 0.32"
gleam_http = "~> 3.5"
mist = "~> 0.15"
gleam_erlang = "~> 0.24"
gleam_otp = "~> 0.9"
simplifile = "~> 1.2"
juno = "~> 1.2"
gleam_json = "~> 0.7"

[dev-dependencies]
gleeunit = "~> 1.0"
